name: Lab6 CI and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

<<<<<<< HEAD
      - name: Build project
        run: npm run build
=======
      - name: Run tests
        run: npm test

      - name: Build project
        run: npm run start
>>>>>>> a204a2277e12bffd8a0f785f690affdcfeb7fadd

      - name: Deploy to GitHub Pages
        env:
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
          USER_NAME: ${{ secrets.USER_NAME }}
          USER_TOKEN: ${{ secrets.USER_TOKEN }}
        if: github.ref == 'refs/heads/master'
        run: |
          git config --global user.name $USER_NAME
          git config --global user.email $USER_EMAIL
          git remote set-url origin https://x-access-token:${{ secrets.USER_TOKEN }}@github.com/${{ github.repository }}.git
          npm run deploy
